BEGIN;

CREATE TABLE PAYMENT_LINKS (
  ID BIGSERIAL PRIMARY KEY,
  DESCRIPTION TEXT NOT NULL,
  AMOUNT DECIMAL(65, 2),
  REFERENCE VARCHAR(100) UNIQUE,
  STATUS VARCHAR(20) DEFAULT 'enabled',
  CREATED_AT TIMESTAMP DEFAULT NOW()
);

COMMIT;