// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package queries

import (
	"database/sql"
)

type PaymentLink struct {
	ID          int64
	Description string
	Amount      sql.NullString
	Reference   sql.NullString
	Status      sql.NullString
	CreatedAt   sql.NullTime
}
